In [2]:
def my_function():
    pass

In [4]:
def my_sq(x):
    return x ** 2

In [5]:
my_sq(4)

16

In [8]:
assert my_sq(4) == 16

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame({'a':[10,20,30],
                  'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [11]:
df['a'] * 2

0    20
1    40
2    60
Name: a, dtype: int64

In [12]:
def my_sq(x):
    return x ** 2

In [14]:
type(df['a'])

pandas.core.series.Series

In [15]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [16]:
def my_exp(x, e):
    return x ** e

In [18]:
assert my_exp(2, 2) == 4

In [19]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [22]:
df['a'].apply(lambda a: my_exp(2, a))

0          1024
1       1048576
2    1073741824
Name: a, dtype: int64

In [25]:
def my_exp2(e, x):
    return my_exp(x, e)

In [26]:
df['a'].apply(my_exp2, x=2)

0          1024
1       1048576
2    1073741824
Name: a, dtype: int64

In [30]:
def print_me(x):
    print(x)

In [28]:
print_me('hello')

hello


In [29]:
df.apply(print_me, axis='index')

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [31]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [32]:
assert avg_3(0, 5, 10) == 5

In [34]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [37]:
import numpy as np

def avg_3_apply(col):
    # return np.sum(col) / 3
    return np.mean(col)

In [38]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [39]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [41]:
df.apply(avg_3_apply, axis='columns')

IndexError: ('index out of bounds', 'occurred at index 0')

In [42]:
df

a   b
0  10  20
1  20  30
2  30  40

In [47]:
def avg_2(x, y):
    return (x + y) / 2

In [44]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [49]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [50]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [51]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [56]:
(df['a'] == 20)

0    False
1     True
2    False
Name: a, dtype: bool

In [57]:
(df['a'] == 20).all()

False

In [58]:
avg_2_mod(10, 20)

15.0

In [59]:
avg_2_mod(20, 30)

nan

In [60]:
import numpy as np

In [61]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [62]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [64]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [65]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [66]:
import numba

In [67]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [68]:
v_avg_2_mod_numba(df['a'], df['b'])

ValueError: cannot determine Numba type of <class 'pandas.core.series.Series'>

In [69]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [70]:
%%timeit
avg_2(df['a'], df['b'])

240 µs ± 4.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [71]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

123 µs ± 1.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [72]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

5.45 µs ± 95.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# exercise

- Look at the table3 dataset

Write a function that takes a value of rate and parses out the total population

Set the population to a new column

In [73]:
tbl3 = pd.read_csv('../data/table3.csv')
tbl3

country  year               rate
0  Afghanistan  1999       745/19987071
1  Afghanistan  2000      2666/20595360
2       Brazil  1999    37737/172006362
3       Brazil  2000    80488/174504898
4        China  1999  212258/1272915272
5        China  2000  213766/1280428583